### ISSUE TITLE
JavaGUI selectTab & co don't fail on non existent tabs

### ISSUE THREAD

**Issue by dergo** [qspin/qtaste#162]
When JavaGUI selectTab(), selectTabId() or selectTabTitled() methods are called on an inexistent tab index, tab name or table title respectively, it executes successfully instead of throwing a QTasteTestFailException.

**Comment by remybaranx** [comment]
I think this issue is solved now.
You can check TabbedPaneSelection and TabbedPaneSelectionException tests in Playback demo.

**Comment by dergo** [comment]
TabbedPaneSelection:
- test doc is dummy
- JAVAGUI_INSTANCE_NAME, TAB_TITLE, TAB_ID test data are not documented, in particular special empty value
- doc of steps is dummy
- you should not insert sleeps between dosteps, 
- rename reset() into unselectTab()
- you don't check that the tab selection works, in particular if selectTab(-1) doesn't work, the selection by title and id have nothing to do

TabbedPaneSelectionException:
- JAVAGUI_INSTANCE_NAME, TEST_CASE_ID test data are not documented
- you may not use doStep() in "if", because it will generate bad documentation, so using TEST_CASE_ID is really a bad idea, just use test data for the wrong id, title,...
- rename reset() into unselectTab()
- instead of doing
```
exception = False
try:
   call()
except:
   exception = True
   ...
if not exception:
   fail()
```
do this:
```
try:
   call()
   fail()
except:
   ...
```
- remove the sleep at the end

**Comment by remybaranx** [comment]
Corrections done.

To be able to check that the selection works, I have added 3 new methods in JavaGUI : getSelectedTabIndex, getSelectedTabTitle, getSelectedTabId.

For the TabbedPaneSelectionException, I have changed test data. Now, instead of TEST_CASE_ID (I understand the problem with it), I use SELECTION_METHOD and SELECTION_VALUE. I prefer to do like that instead of doing like in TabbedPaneSelection, because error cases are different in selection by index and selection by title/id.
