### ISSUE TITLE
Save button doesn't save the requirements

### ISSUE THREAD

**Issue by dergo** [qspin/qtaste#181]
- edit a requirement
- * appears to show that it is modified
- click on save button
- requirements are not saved and * is still shown

Only control-s works to save the requirements.

**Comment by remybaranx** [comment]
I fixed this issue -> To validate.

**Comment by dergo** [comment]
Requirements are now saved except if you modify a requirement, don't leave focus from the modified requirement then press save button, in that case the modification in the focused cell is reverted!
While it works if you press control-s.

Same behavior on the test data editor.

**Comment by remybaranx** [comment]
By "don't leave focus" you mean "don't validate your modification by pressing on enter" right ? Because if I validate my requirement modification by pressing enter and the focus stays on the requirement cell, the modification is saved by pressing on the save button.

So, if the user presses the save button, you want to save requirement or test data modification, even if the requirement or the test data is being modified, right ?

**Comment by dergo** [comment]
Yes and yes, same behavior as pressing control-S.

**Comment by remybaranx** [comment]
Done for requirement and test data editors --> to validate.

**Comment by lvboque** [comment]
Could you check if it was fixed in 2.3.0 and simply regenerate the release notes?
Thks

**Comment by simjan** [comment]
included in 2.3.0
