### ISSUE TITLE
JAVAGUI isAPopup method implementation is too restrictive

### ISSUE THREAD

**Issue by aschoof** [qspin/qtaste#210]
Reading the implementation of the method isAPopup of JAVAGUI it seems it's too restrictive.
Indeed according to the implementation the JDialog popup MUST contain a JOptionPane. This is often the case, but not always ...
I'd suggest to just remove this test.

**Comment by dergo** [comment]
Yet we could consider a more generic kind of popup, not just JOptionPane, we could not use getPopupText(), clickOnPopupButton() nor setPopupValue() methods on it, so it would not be very useful, only isPopupDisplayed() and getPopupRawName() methods would be usable.
And the implementation of these methods should then be changed to take into account popups which are not a JOptionPane.

I proposed a workaround for the specific issue: just check that a component of the JDialog (text field or button or other) is visible by using the isVisible() method, instead of using the isPopupDisplayed() method.

**Comment by dergo** [comment]
Fixed issue.

Note that clickOnPopupButton() and setPopupValue() are actually usable on non JOptionPane also.

To be validated.

**Comment by dergo** [comment]
Tested: it works but has a nasty side-effect.

Previously we were doing things like the following, because all our popups had an "Ok" button:
    while myProgram.isPopupDisplayed():
        myProgram.clickOnPopupButton("Ok")
This doesn't work anymore with the fix if a dialog without "Ok" button is opened, because in this case it will try to find the "Ok" button for something like 5s (every 1s) and then fail.

So a method hasPopupButton(text) method would have to be added to be able to do this instead:
    while myProgram.isPopupDisplayed():
        if myProgram.hasPopupButton("Ok"):
            myProgram.clickOnPopupButton("Ok")

For now, I don't think it's worth the change, as there is the workaround I proposed, so I will revert the fix and close the issue.
