### ISSUE TITLE
FILE_ keys in getValue

### ISSUE THREAD

**Issue by bdaene** [qspin/qtaste#236]
Keys with a name starting in "FILE_" have a different behavior than other name in different functions like TestDataImpl.getValue(String key).
This not explained in the documentation and we had a strange bug that in the end was because the key name was modified removing the FILE_ part.

Should be documented and/or have a method to get the testCaseDirectory from the test script.

**Comment by dergo** [comment]
Actually, this is already documented in the user manual (which you can access from the Help menu in QTaste or from Github), section 8.2 Test data:
...
There are some special test data associated with the QTaste test engine:
Test data name | Comment
----------------- | -----------
COMMENT | This free text variable is used by the Test Designer to comment the values inserted in the line and their impact on the test at run time. This information will be used during the test report generation.
TIMEOUT | This variable is used as a maximum time expressed in seconds for the test execution of one test row. By the default the value is 60 seconds. This value can also be set at the beginning of the script (in order to set the value for all test rows) or in the testdata file is value can differ from one test row to another.
FILE_* | Column names starting with “FILE_” are automatically loaded by the Test Engine and their content can be retrieved by the scripts using the TestData (can be useful for data that need to be used on remote hosts).
...

Is this sufficient or is there still something to be improved ?

**Comment by bdaene** [comment]
Should be sufficient.
